/*

 *
 * Copyright (C) GNU/GPL AVOIR 2008
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 51
 * Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

 */

/*
 * PointerListPanel.java
 *
 * Created on 2009/04/12, 03:05:52
 */
package org.avoir.realtime.gui;

import org.avoir.realtime.gui.main.GUIAccessManager;

/**
 *
 * @author developer
 */
public class PointerListPanel extends javax.swing.JDialog {

    public static int ARROW_UP = 0;
    public static int ARROW_SIDE = 1;
    public static int HAND_LEFT = 2;
    public static int HAND_RIGHT = 3;
    public static int NO_POINTER = 4;
    public static int SELECTED_POINTER = NO_POINTER;

    /** Creates new form PointerListPanel */
    public PointerListPanel() {
        initComponents();
        setModal(true);
    }

    public int getSelectedPointer() {
        return SELECTED_POINTER;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mPanel = new javax.swing.JPanel();
        pointerPanel = new javax.swing.JPanel();
        arrowUpButton = new javax.swing.JButton();
        arrowSideButton = new javax.swing.JButton();
        handLeftButton = new javax.swing.JButton();
        handRightButton = new javax.swing.JButton();
        noPointerButton = new javax.swing.JButton();
        cPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();


        mPanel.setLayout(new java.awt.BorderLayout());

        pointerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Pointer"));
        pointerPanel.setLayout(new java.awt.GridLayout(2, 2));

        arrowUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pointer-arrow_up.png"))); // NOI18N
        arrowUpButton.setBorderPainted(false);
        arrowUpButton.setContentAreaFilled(false);
        arrowUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arrowUpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arrowUpButtonMouseExited(evt);
            }
        });
        arrowUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowUpButtonActionPerformed(evt);
            }
        });
        pointerPanel.add(arrowUpButton);

        arrowSideButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pointer-arrow_side.png"))); // NOI18N
        arrowSideButton.setBorderPainted(false);
        arrowSideButton.setContentAreaFilled(false);
        arrowSideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                arrowSideButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                arrowSideButtonMouseExited(evt);
            }
        });
        arrowSideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowSideButtonActionPerformed(evt);
            }
        });
        pointerPanel.add(arrowSideButton);

        handLeftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pointer-hand_left.png"))); // NOI18N
        handLeftButton.setBorderPainted(false);
        handLeftButton.setContentAreaFilled(false);
        handLeftButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                handLeftButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                handLeftButtonMouseExited(evt);
            }
        });
        handLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handLeftButtonActionPerformed(evt);
            }
        });
        pointerPanel.add(handLeftButton);

        handRightButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pointer-hand_right.png"))); // NOI18N
        handRightButton.setBorderPainted(false);
        handRightButton.setContentAreaFilled(false);
        handRightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                handRightButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                handRightButtonMouseExited(evt);
            }
        });
        handRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handRightButtonActionPerformed(evt);
            }
        });
        pointerPanel.add(handRightButton);

        noPointerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross16.png"))); // NOI18N
        noPointerButton.setText("None");
        noPointerButton.setBorderPainted(false);
        noPointerButton.setContentAreaFilled(false);
        noPointerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noPointerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noPointerButtonMouseExited(evt);
            }
        });
        noPointerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPointerButtonActionPerformed(evt);
            }
        });
        pointerPanel.add(noPointerButton);

        mPanel.add(pointerPanel, java.awt.BorderLayout.CENTER);

        cPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        cPanel.add(cancelButton);

        mPanel.add(cPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void arrowUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowUpButtonActionPerformed
        SELECTED_POINTER = ARROW_UP;
        //GUIAccessManager.mf.getWhiteboardPanel().setWhiteboardToolbarEnabled(false);
        arrowUpButton.setContentAreaFilled(arrowUpButton.isSelected());
        setVisible(false);
    }//GEN-LAST:event_arrowUpButtonActionPerformed

    private void arrowSideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowSideButtonActionPerformed
        SELECTED_POINTER = ARROW_SIDE;
        //GUIAccessManager.mf.getWhiteboardPanel().setWhiteboardToolbarEnabled(false);

        setVisible(false);
    }//GEN-LAST:event_arrowSideButtonActionPerformed

    private void handLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handLeftButtonActionPerformed
        SELECTED_POINTER = HAND_LEFT;
       // GUIAccessManager.mf.getWhiteboardPanel().setWhiteboardToolbarEnabled(false);
        setVisible(false);
    }//GEN-LAST:event_handLeftButtonActionPerformed

    private void handRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handRightButtonActionPerformed
        SELECTED_POINTER = HAND_RIGHT;
      //  GUIAccessManager.mf.getWhiteboardPanel().setWhiteboardToolbarEnabled(false);
        setVisible(false);
    }//GEN-LAST:event_handRightButtonActionPerformed

    private void arrowUpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowUpButtonMouseEntered
        arrowUpButton.setBorderPainted(true);
    }//GEN-LAST:event_arrowUpButtonMouseEntered

    private void arrowUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowUpButtonMouseExited
        arrowUpButton.setBorderPainted(false);
    }//GEN-LAST:event_arrowUpButtonMouseExited

    private void arrowSideButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowSideButtonMouseEntered
        arrowSideButton.setBorderPainted(true);
    }//GEN-LAST:event_arrowSideButtonMouseEntered

    private void arrowSideButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arrowSideButtonMouseExited
        arrowSideButton.setBorderPainted(false);
    }//GEN-LAST:event_arrowSideButtonMouseExited

    private void handLeftButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handLeftButtonMouseEntered
        handLeftButton.setBorderPainted(true);
    }//GEN-LAST:event_handLeftButtonMouseEntered

    private void handLeftButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handLeftButtonMouseExited
        handLeftButton.setBorderPainted(false);
    }//GEN-LAST:event_handLeftButtonMouseExited

    private void handRightButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handRightButtonMouseEntered
        handRightButton.setBorderPainted(true);
    }//GEN-LAST:event_handRightButtonMouseEntered

    private void handRightButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_handRightButtonMouseExited
        handRightButton.setBorderPainted(false);
    }//GEN-LAST:event_handRightButtonMouseExited

    private void noPointerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPointerButtonActionPerformed
        SELECTED_POINTER = NO_POINTER;
        //GUIAccessManager.mf.getWhiteboardPanel().setWhiteboardToolbarEnabled(true);
        GUIAccessManager.mf.adjustSize();
        dispose();
    }//GEN-LAST:event_noPointerButtonActionPerformed

    private void noPointerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noPointerButtonMouseEntered
        noPointerButton.setBorderPainted(true);
    }//GEN-LAST:event_noPointerButtonMouseEntered

    private void noPointerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noPointerButtonMouseExited
        noPointerButton.setBorderPainted(false);
    }//GEN-LAST:event_noPointerButtonMouseExited

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arrowSideButton;
    private javax.swing.JButton arrowUpButton;
    private javax.swing.JPanel cPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton handLeftButton;
    private javax.swing.JButton handRightButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mPanel;
    private javax.swing.JButton noPointerButton;
    private javax.swing.JPanel pointerPanel;
    // End of variables declaration//GEN-END:variables
}
