/*
 * MainAppletGUI.java
 *
 * Created on 11 May 2008, 01:44
 */

package avoir.realtime.tcp.client.applet;

/**
 *
 * @author  developer
 */
public class MainAppletGUI extends javax.swing.JPanel {

    /** Creates new form MainAppletGUI */
    public MainAppletGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Main GUI");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        mPanel.setLayout(new java.awt.BorderLayout());
        add(mPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mPanel;
    // End of variables declaration//GEN-END:variables

}
