/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JavaVersionWarningDialog.java
 *
 * Created on 2009/11/25, 5:08:24 PM
 */
package org.avoir.realtime.gui.main;

import org.avoir.realtime.common.util.GeneralUtil;

/**
 *
 * @author kim
 */
public class JavaVersionWarningDialog extends javax.swing.JDialog {

    /** Creates new form JavaVersionWarningDialog */
    public JavaVersionWarningDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        showOption.setSelected(new Boolean(GeneralUtil.getProperty("show.java.warning")));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        showOption = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoField = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton);

        showOption.setText("Do not show this message again");
        showOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOptionActionPerformed(evt);
            }
        });
        jPanel1.add(showOption);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        infoField.setContentType("text/html");
        infoField.setEditable(false);
        infoField.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n        It seems your java version is less than 1.6. <br>\n       In order to utilize full functionality of Realtime tools, upgrade to latest  version from<br>\n      <a href=\"http://www.java.com\">www.java.com</a>\n    </p>\n  </body>\n</html>\n");
        jScrollPane1.setViewportView(infoField);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOptionActionPerformed
        GeneralUtil.saveProperty("show.java.warning", showOption.isSelected() + "");
    }//GEN-LAST:event_showOptionActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JavaVersionWarningDialog dialog = new JavaVersionWarningDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane infoField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox showOption;
    // End of variables declaration//GEN-END:variables
}
