/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PermissionsPanel.java
 *
 * Created on 2009/08/22, 7:50:52 PM
 */
package org.avoir.realtime.gui.userlist;

import javax.swing.JCheckBox;

/**
 *
 * @author kim
 */
public class PermissionsPanel extends javax.swing.JPanel {

    /** Creates new form PermissionsPanel */
    public PermissionsPanel() {
        initComponents();
    }

    public JCheckBox getAdminOpt() {
        return adminOpt;
    }

    public JCheckBox getMicOpt() {
        return micOpt;
    }

    public JCheckBox getWhiteboardOpt() {
        return whiteboardOpt;
    }

    /**
     * getters
     */
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        micOpt = new javax.swing.JCheckBox();
        adminOpt = new javax.swing.JCheckBox();
        whiteboardOpt = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        micOpt.setText("Microphone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(micOpt, gridBagConstraints);

        adminOpt.setText("Adminstrative");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(adminOpt, gridBagConstraints);

        whiteboardOpt.setText("Whiteboard");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(whiteboardOpt, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminOpt;
    private javax.swing.JCheckBox micOpt;
    private javax.swing.JCheckBox whiteboardOpt;
    // End of variables declaration//GEN-END:variables
}
