<?php
/* ----------- data class extends dbTable for tbl_calendar------------*/
// security check - must be included in all scripts
if (!$GLOBALS['kewl_entry_point_run'])
    {
        die("You cannot view this page directly");
    }

/**
* Calendar Generator Class
*
* @author Tohir Solomons
* @copyright (c) 2005 University of the Western Cape
* @package calendarbase
* @version 1
*
* This class was written based on a function written by Keith Devens
* The original function PHP Calendar (version 2.3), can be found at:
* http://keithdevens.com/software/php_calendar
* Licence: http://keithdevens.com/software/license
*
* Changes that occurred:
* - Parameters of the function were moved to variables of the class
* - The original function was called 'generate_calendar'. In conformity with KEWL.Nextgen, it has been called show().
* - Names of the month and days are generated by KEWL.NextGen's language database
* - The ability has been added to have titles within the day
* - CSS styles have been coded into the class
*
* A note on the events array:
*
* The array is in the format $event[$day] => $ content, where:
* - $event is the array holding the events
* - $day is the day of the month
* - $content is the content you want to have appear
*
* An example would be: $event['25'] => 'My Birthday';
*
* The month and year would be determine by the $month and $year variables
*/
class calendargenerator extends object
{
    /**
    * @var year The Year for which the calendar should be generated
    */
    public $year;

    /**
    * @var month The Month for which the calendar should be generated
    */
    public $month;

    /**
    * @var events An array containing a list of events
    */
    public $events;

    /**
    * @var size The size of the calendar. either big or small
    */
    public $size;

    /**
    * @var first_day The First Day of the Week in the Calendar
    */
    public $first_day;

    /**
    * Constructor method for the class
    *
    * @access public
    * @param void
    * @return void
    */
    public function init()
    {
        $this->objSimpleCal =& $this->getObject('datetime','utilities');
        $this->objDateFunctions =& $this->getObject('datefunctions');
        $this->month = date('m');
        $this->year = date('Y');
        $this->size = 'big';
        $this->first_day = 0;
    }

    /**
    * Method to set the events array
    *
    * @access public
    * @param array $events List of Events
    * @return void
    */
    public function setEvents($events)
    {
        $this->events = $events;
    }

    /**
    * Method to generate the calendar
    *
    * @access public
    * @param void
    * @return string
    */
    public function show()
    {
    	$this->appendArrayVar('headerParams','<link href="modules/calendarbase/resources/calendarstyle.css" rel="stylesheet" type="text/css"/>');
        $first_of_month = gmmktime(0,0,0,$this->month,1,$this->year);
        #remember that mktime will automatically correct if invalid dates are entered
        # for instance, mktime(0,0,0,12,32,1997) will be the date for Jan 1, 1998
        # this provides a built in "rounding" feature to generate_calendar()

        $day_names = array(); #generate all the day names according to the current locale
        

        if ($this->first_day == 0) {
            $this->objSimpleCal->startweek='sun';
        }
       
        if ($this->size == 'big') {
            $day_names = $this->objSimpleCal->getDaysAsArray();
            $toc = 'TOC';
            $extraCss = ' mainTable'.$toc;
            $width = 'width="14%"';
        } else {
            $day_names = $this->objSimpleCal->getDaysAsArray('1letter');
            $toc = '';
            $extraCss = 'mainTable';
            $width = '';
        }

        list($month, $year, $month_name, $weekday) = explode(',',gmstrftime('%m,%Y,%B,%w',$first_of_month));
        $weekday = ($weekday + 7 - $this->first_day) % 7; #adjust for $this->first_day

        $calendar = '<table class="'.$extraCss.'" cellspacing="1" cellpadding="0" border="0">';
        if ($this->size != 'big') {
            $calendar .= '<thead><th  colspan="7" align="center">'.$this->objSimpleCal->monthFull($this->month).' '.$this->year.'</th></thead>';
        }
        $calendar .= '<thead class="dayNamesText'.$toc.'">';

        foreach($day_names as $d)
        {
            $calendar .= '<th class="dayNamesRow'.$toc.'" '.$width.'>'.$d.'</th>';
        }

        $calendar .= "</thead>\n<tr class=\"rows'.$toc.'\">";

        // Initial Days from previous month
        if($weekday > 0) {
            for ($i=0; $i < $weekday; $i++)
            {
                $calendar .= '<td class="sOtherTOC">&nbsp;</td>';
            }
        } // END - Initial Days from previous month

        //return $this->showSimple($day_names, $weekday);

        for($day=1,$days_in_month=gmdate('t',$first_of_month); $day<=$days_in_month; $day++,$weekday++)
        {
            if($weekday == 7){
                $weekday   = 0; // start a new week
                
                $calendar .= "</tr>\n<tr class=\"rows".$toc."\">";
            }
            if(isset($this->events[$day]) ){

                $content = $this->events[$day];

                if(is_null($content)) {
                    $content  = $day;
                }

                if ($this->year == date('Y') && $this->month == date('n') && $day == date('j') ){
                    $cssClass = 's20'.$toc;
                } else {
                    $cssClass = 's20'.$toc;
                }
                if ($this->size == 'big') {
                    $calendar .= '<td class="'.$cssClass.'"><div class="daynum'.$toc.'"><a href="#'.$day.'">'.$day.'</a></div>';
                } else {
                    $calendar .= '<td class="'.$cssClass.'">'.$day;
                }

                if (isset($content) && $this->size=='big') {
                    $calendar .= $content;
                }
                $calendar .= '</td>';
            }
            else if ($this->year == date('Y') && $this->month == date('n') && $day == date('j') ){
                $calendar .= '<td class="s20'.$toc.'"><div class="today'.$toc.'">'.$day.'</div></td>';
            }
            else {
            	
            	$cssClass = ($weekday == 0 || $weekday==6) ? 's20'.$toc.'0' : 's20'.$toc; 
                $calendar .= '<td class="'.$cssClass.'"><div class="daynum'.$toc.'">'.$day.'</div></td>';
            }
        }

        // Rest of days from next month
        if($weekday != 7) {
            for ($i=0; $i < (7 - $weekday); $i++)
            {
                $calendar .= '<td class="sOther'.$toc.'">&nbsp;</td>';
            }
        }// END - Rest of days from next month

        return $calendar."</tr>\n</table>\n";
        
       
    }
    
    /**
     * Method to show the simple calendar
     * @return string
     * @author Wesley Nitsckie
     * @param 
     * @param 
     * @access public
     */
    public function showSimple($day_names , $weekday)
    {
        
        $str = '<table class="mainTable" cellspacing="1" cellpadding="0">';
        $str .= ' <tr>
          <td class="monthYearText monthYearRow" colspan="7" title="EasyPHPCalendar 6">';
        $str .='    August 2006';
        $str .='  </td>
         </tr>
         <tr class="dayNamesText">';
        foreach ($day_names as $d) {
        	$str .= '<td class="dayNamesRow" width="14%">W</td>';
        }
          
          $str .= '</tr>
         <tr class="rows" onclick="location.href=\'http://www.easyphpcalendar.com/demo.php\';" style="cursor: pointer;">';
          if($weekday > 0) {
            for ($i=0; $i < $weekday; $i++)
            {
                $str .= '<td class="sOther">&nbsp;</td>';
            }
        }
          $str .='
          <td class="s2">1</td>
          <td class="s2">2</td>
        
          <td class="s2">3</td>
          <td class="s2">4</td>
          <td class="s200">5</td>
        </tr>
         <tr class="rows" onclick="location.href=\'http://www.easyphpcalendar.com/demo.php\';" style="cursor: pointer;">
          <td class="s22">6</td>
          <td class="s22">7</td>
        
          <td class="s22">8</td>
          <td class="s2">9</td>
          <td class="s24">10</td>
          <td class="s23">11</td>
          <td class="s23">12</td>
        </tr>
         <tr class="rows" onclick="location.href=\'http://www.easyphpcalendar.com/demo.php\';" style="cursor: pointer;">
        
          <td class="s23">13</td>
          <td class="s23">14</td>
          <td class="s23">15</td>
          <td class="s23">16</td>
          <td class="s23">17</td>
          <td class="s2">18</td>
        
          <td class="s200">19</td>
        </tr>
         <tr class="rows" onclick="location.href=\'http://www.easyphpcalendar.com/demo.php\';" style="cursor: pointer;">
          <td class="s200">20</td>
          <td class="s2">21</td>
          <td class="s2">22</td>
          <td class="s22 today">23</td>
        
          <td class="s2">24</td>
          <td class="s2">25</td>
          <td class="s200">26</td>
        </tr>
         <tr class="rows" onclick="location.href=\'http://www.easyphpcalendar.com/demo.php\';" style="cursor: pointer;">
          <td class="s200">27</td>
          <td class="s2">28</td>
        
          <td class="s2">29</td>
          <td class="s2">30</td>
          <td class="s22">31</td>
          <td class="sOther">1</td>
          <td class="sOther">2</td>
        </tr>
         <tr class="rows" onclick="location.href=\'http://www.easyphpcalendar.com/demo.php\';" style="cursor: pointer;">
        
          <td class="sOther">3</td>
          <td class="sOther">4</td>
          <td class="sOther">5</td>
          <td class="sOther">6</td>
          <td class="sOther">7</td>
          <td class="sOther">8</td>
        
          <td class="sOther">9</td>
        </tr>
        </table>';
        
        return $str;
            
    }

}
?>