/*
 * FilterFrame.java
 *
 * Created on 02 June 2008, 01:34
 */
package avoir.realtime.tcp.base;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import javax.swing.JOptionPane;

/**
 *
 * @author  developer
 */
public class FilterFrame extends javax.swing.JFrame implements ClipboardOwner {

    String help1 = "This filter can be pasted in any tool that supports filters.\n" +
            "It will be replaced by the live presentation session when the page is displayed.\n";
    String remoteFilter;
    Clipboard clipBoard = Toolkit.getDefaultToolkit().getSystemClipboard();

    /** Creates new form FilterFrame */
    public FilterFrame(String filter) {
        initComponents();
        this.remoteFilter = filter;
        this.localFilterField.setText(filter);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        mPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        localFilterField = new javax.swing.JTextField();
        help1Button = new javax.swing.JButton();
        copy2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realtime Chisimba Filter");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 204, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chisimba Filters");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        mPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Filter");
        jLabel2.setMaximumSize(new java.awt.Dimension(300, 19));
        jLabel2.setMinimumSize(new java.awt.Dimension(300, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        mPanel.add(jLabel2, gridBagConstraints);

        localFilterField.setMinimumSize(new java.awt.Dimension(400, 19));
        localFilterField.setPreferredSize(new java.awt.Dimension(300, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        mPanel.add(localFilterField, gridBagConstraints);

        help1Button.setText("What does it mean?");
        help1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help1ButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        mPanel.add(help1Button, gridBagConstraints);

        copy2.setText("Copy");
        copy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copy2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        mPanel.add(copy2, gridBagConstraints);

        getContentPane().add(mPanel, java.awt.BorderLayout.CENTER);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(closeButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    dispose();// TODO add your handling code here:
}//GEN-LAST:event_closeButtonActionPerformed

private void help1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help1ButtonActionPerformed
    JOptionPane.showMessageDialog(this, help1);
}//GEN-LAST:event_help1ButtonActionPerformed

private void copy2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
    
localFilterField.copy();

};                                                                          

    public void lostOwnership(Clipboard arg0, Transferable arg1) {
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton copy2;
    private javax.swing.JButton help1Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField localFilterField;
    private javax.swing.JPanel mPanel;
    // End of variables declaration//GEN-END:variables

}
