/**
 * 	$Id: ChatRoom.java,v 1.3 2007/02/02 10:59:15 davidwaf Exp $
 *
 *  Copyright (C) GNU/GPL AVOIR 2007
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
package avoir.realtime.tcp.base;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.Transferable;
import javax.swing.JOptionPane;

/**
 * This displays the filters generated from a presentation. Filters can be pasted
 * into other tools - embbeded
 * @author  david wafula
 */
public class FilterFrame extends javax.swing.JFrame implements ClipboardOwner {

    String help1 = "This filter can be pasted into any tool that supports filters.\n" +
            "It will be replaced by the presentation when the page is displayed.\n" +
            "Note that this filter can be used on the same server or any remote\n" +
            "Chisimba-powered site or site that implements the Chisimba webpresent filter.";
    String help2 =
            "This HTML snippet can be pasted into any website tool on any system\n" +
            "that allows you to past raw HTML into your content.\n" +
            "Select all the contents of the box (CONTROL+A), copy it (CONTROL+C)\n" +
            " and paste it into your site in edit raw HTML mode.";
    Clipboard clipBoard = Toolkit.getDefaultToolkit().getSystemClipboard();

    /** Creates new form FilterFrame */
    public FilterFrame(String filter, String embbed) {
        initComponents();
        embbedField.setText(embbed);
        filterField.setText(filter);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mPanel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        filterPanel = new javax.swing.JPanel();
        filterFieldSP = new javax.swing.JScrollPane();
        filterField = new javax.swing.JTextArea();
        cPanel = new javax.swing.JPanel();
        selectyAllandCopyButton = new javax.swing.JButton();
        help1Button = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        embbedPanel = new javax.swing.JPanel();
        embbedFieldSP = new javax.swing.JScrollPane();
        embbedField = new javax.swing.JTextArea();
        cPanel1 = new javax.swing.JPanel();
        selectyAllandCopyButton1 = new javax.swing.JButton();
        help1Button1 = new javax.swing.JButton();
        closeButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realtime Chisimba Filter");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel1.setForeground(new java.awt.Color(255, 204, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chisimba Filters");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        mPanel.setLayout(new java.awt.BorderLayout());

        filterPanel.setLayout(new java.awt.BorderLayout());

        filterField.setColumns(18);
        filterField.setEditable(false);
        filterField.setLineWrap(true);
        filterField.setRows(5);
        filterFieldSP.setViewportView(filterField);

        filterPanel.add(filterFieldSP, java.awt.BorderLayout.CENTER);

        selectyAllandCopyButton.setText("Copy");
        selectyAllandCopyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectyAllandCopyButtonActionPerformed(evt);
            }
        });
        cPanel.add(selectyAllandCopyButton);

        help1Button.setText("What does it mean?");
        help1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help1ButtonActionPerformed(evt);
            }
        });
        cPanel.add(help1Button);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        cPanel.add(closeButton);

        filterPanel.add(cPanel, java.awt.BorderLayout.PAGE_END);

        tabbedPane.addTab("Chisimba Filter", filterPanel);

        embbedPanel.setLayout(new java.awt.BorderLayout());

        embbedField.setColumns(20);
        embbedField.setLineWrap(true);
        embbedField.setRows(5);
        embbedFieldSP.setViewportView(embbedField);

        embbedPanel.add(embbedFieldSP, java.awt.BorderLayout.CENTER);

        selectyAllandCopyButton1.setText("Copy");
        selectyAllandCopyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectyAllandCopyButton1ActionPerformed(evt);
            }
        });
        cPanel1.add(selectyAllandCopyButton1);

        help1Button1.setText("What does it mean?");
        help1Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                help1Button1ActionPerformed(evt);
            }
        });
        cPanel1.add(help1Button1);

        closeButton1.setText("Close");
        closeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton1ActionPerformed(evt);
            }
        });
        cPanel1.add(closeButton1);

        embbedPanel.add(cPanel1, java.awt.BorderLayout.PAGE_END);

        tabbedPane.addTab("HTML Embbed", embbedPanel);

        mPanel.add(tabbedPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(mPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * closes the fiter frame
     * @param evt
     */
private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    dispose();// TODO add your handling code here:
}//GEN-LAST:event_closeButtonActionPerformed

private void help1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help1ButtonActionPerformed
    JOptionPane.showMessageDialog(this, help1);
}//GEN-LAST:event_help1ButtonActionPerformed

private void selectyAllandCopyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectyAllandCopyButtonActionPerformed


    filterField.selectAll();
    filterField.copy();

}//GEN-LAST:event_selectyAllandCopyButtonActionPerformed

private void selectyAllandCopyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectyAllandCopyButton1ActionPerformed

    embbedField.selectAll();
    embbedField.copy();
}//GEN-LAST:event_selectyAllandCopyButton1ActionPerformed

private void help1Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_help1Button1ActionPerformed
    JOptionPane.showMessageDialog(this, help2);
}//GEN-LAST:event_help1Button1ActionPerformed

private void closeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton1ActionPerformed
    dispose();
}//GEN-LAST:event_closeButton1ActionPerformed

private void copy2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
    
filterField.copy();

};                                                                          

    public void lostOwnership(Clipboard arg0, Transferable arg1) {
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cPanel;
    private javax.swing.JPanel cPanel1;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton closeButton1;
    private javax.swing.JTextArea embbedField;
    private javax.swing.JScrollPane embbedFieldSP;
    private javax.swing.JPanel embbedPanel;
    private javax.swing.JTextArea filterField;
    private javax.swing.JScrollPane filterFieldSP;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JButton help1Button;
    private javax.swing.JButton help1Button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mPanel;
    private javax.swing.JButton selectyAllandCopyButton;
    private javax.swing.JButton selectyAllandCopyButton1;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

}
