/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package avoir.realtime.tcp.base;

import java.io.IOException;
import java.util.Properties;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.File;
import java.io.PrintWriter;
import java.io.FileWriter;
 
/**
 *
 * @author developer
 */
public class RealtimeOptions {

    public RealtimeOptions() {

        init();

        loadProperties();
    }
    Properties props;
    //user can install the app in any folder..so use the System class to figure out where
    String fileName = avoir.realtime.tcp.common.Constants.getRealtimeHome() + "/conf/realtime.properties";
    String defaultFileName = avoir.realtime.tcp.common.Constants.getRealtimeHome() + "/conf/default.properties";
    String confDir = avoir.realtime.tcp.common.Constants.getRealtimeHome() + "/conf/";
    String binDir = avoir.realtime.tcp.common.Constants.getRealtimeHome() + "/bin/";
    String libDir = avoir.realtime.tcp.common.Constants.getRealtimeHome() + "/lib/";
    String soundsDir = avoir.realtime.tcp.common.Constants.getRealtimeHome() + "/sounds/";

    private void write(String filename) {
        write(filename, "DirectConnection=true");
        write(filename, "SystemProxy=false");
        write(filename, "ManualProxy=false");
        write(filename, "ProxyHost=");
        write(filename, "ProxyPort=0");
        write(filename, "UseOnlineSuperNodes=true");
        write(filename, "UseCache=true");
    }

    public void init() {
        File confFile = new File(confDir);
        File defaultFile = new File(defaultFileName);
        File file = new File(fileName);
        if (!confFile.exists()) {
            confFile.mkdirs();
        }
        if (!defaultFile.exists()) {
            write(defaultFileName);

        }
        if (!file.exists()) {
            write(fileName);
        }
        File binFile = new File(binDir);
        if (!binFile.exists()) {
            binFile.mkdirs();
        }
        File libFile = new File(libDir);
        if (!libFile.exists()) {
            libFile.mkdirs();
        }
        File soundsFile = new File(soundsDir);
        if (!soundsFile.exists()) {
            soundsFile.mkdirs();
        }
        loadProperties();
    }

    private void write(String filename, String txt) {
        try {
            FileWriter outFile = new FileWriter(filename, true);
            PrintWriter printWriter = new PrintWriter(outFile);
            printWriter.println(txt);
            printWriter.close();
        } catch (IOException e) {
            e.printStackTrace();
        }


    }

    public void saveProperty(String prop, String value) {
        try {
            FileOutputStream out = new FileOutputStream(fileName);
            props.put(prop, value);
            props.store(out,
                    "---DO NOT EDIT THIS FILE IT IS SYSTEM GENERATED---");
            out.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * returns true if direct connection is used
     * @return
     */
    public boolean useDirectConnection() {
        return new Boolean(getProperty("DirectConnection")).booleanValue();
    }

    /**
     * Returns true if system proxy is used
     * @return
     */
    public boolean useSystemProxy() {
        return new Boolean(getProperty("SystemProxy")).booleanValue();
    }

    public boolean useCache() {
        String useCache = getProperty("UseCache");
        if (useCache == null) {
            return true;
        }
        if (useCache.equals("")) {
            return true;
        }
        return new Boolean(useCache).booleanValue();
    }

    /**
     * Returns true if manual proxy is used
     * @return
     */
    public boolean useManualProxy() {
        return new Boolean(getProperty("ManualProxy")).booleanValue();
    }

    /**
     * returns true if configured to use online super nodes
     * @return
     */
    public boolean useOnlineSuperNodes() {
        return new Boolean(getProperty("UseOnlineSuperNodes")).booleanValue();
    }

    /**
     * 
     * @param status
     */
    public void setUseOnlineSuperNodes(boolean status) {
        saveProperty("UseOnlineSuperNodes", status + "");
    }

    /**
     * Gets current internet proxy host value
     * @return
     */
    public String getProxyHost() {
        return getProperty("ProxyHost");
    }

    public void setProxyHost(String host) {
        saveProperty("ProxyHost", host);
    }

    public String getProxyPort() {
        return getProperty("ProxyPort");
    }

    public void setRealtimeProxyPort(String port) {
        saveProperty("RealtimeProxyPort", port);
    }

    public String getRealtimeProxyPort() {
        return getProperty("RealtimeProxyPort");
    }

    public void setProxyPort(String port) {
        saveProperty("ProxyPort", port);
    }

    public String getProperty(String prop) {
        return props.getProperty(prop);
    }

    public void setUseDirectConnection(boolean use) {
        saveProperty("DirectConnection", use + "");
    }

    public void setUseManualProxy(boolean use) {
        saveProperty("ManualProxy", use + "");
    }

    public void setUseSystemProxy(boolean use) {
        saveProperty("SystemProxy", use + "");
    }

    public void setUseCache(boolean use) {
        saveProperty("UseCache", use + "");
    }

    public String getConnectionMode() {
        if (useDirectConnection()) {
            return "Direct Connection";
        } else if (useSystemProxy()) {
            return "System Proxy";
        } else {
            return "Manual Proxy Configuration";
        }
    }

    public void loadProperties() {
        try {

            // create and load default properties
            Properties defaultProps = new Properties();
            FileInputStream in = new FileInputStream(fileName);
            defaultProps.load(in);
            in.close();

            // create program properties with default
            props = new Properties(defaultProps);

            // now load properties from last invocation
            in = new FileInputStream(fileName);
            props.load(in);
            in.close();

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}

