package avoir.realtime.appsharing;

import java.io.IOException;
import java.util.Properties;
import java.io.FileInputStream;
import java.io.FileOutputStream;

/**
 * <p>Title: </p>
 *
 * <p>Description: This class is used for manipulating the application properties/p>
 *
 * @version 1.0
 */
public class AppProps {

    static Properties props;
    //user can install the app in any folder..so use the System class to figure out where
    static String fileName = "server.properties";
    

    static {
        loadProperties();
    }
    ;

    public static void saveProperty(String prop, String value) {
        try {
            FileOutputStream out = new FileOutputStream(fileName);
            props.put(prop, value);
            props.store(out,
                    "---DO NOT EDIT THIS FILE IT IS SYSTEM GENERATED---");
            out.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public static String getProperty(String prop) {
        return props.getProperty(prop);
    }
    ;

    public static void loadProperties() {
        try {

            // create and load default properties
            Properties defaultProps = new Properties();
            FileInputStream in = new FileInputStream(fileName);
            defaultProps.load(in);
            in.close();

            // create program properties with default
            props = new Properties(defaultProps);

            // now load properties from last invocation
            in = new FileInputStream(fileName);
            props.load(in);
            in.close();

        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}
