/*
 * AppShareFrame.java
 *
 * Created on 14 September 2008, 12:19
 */
package avoir.realtime.appsharing;

import avoir.realtime.common.TCPSocket;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  developer
 */
public class AppShareFrame extends javax.swing.JFrame {

    private Java2ScreenScraper ss;
    private Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    private TCPSocket tcpClient;

    /** Creates new form AppShareFrame */
    public AppShareFrame() {
        initComponents();
    }

    public AppShareFrame(final TCPSocket tcpClient, String sessionId) {
        this();
        this.tcpClient = tcpClient;

        try {
            ss = new Java2ScreenScraper(tcpClient, sessionId);


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error occurred cannot startappsharing");
            ex.printStackTrace();
        }
    }

    protected void stopScraping() {
        startButton.setEnabled(true);
        stopButton.setEnabled(false);

        ss.stopScraping();
    }

    protected void startScraping() {
        stopButton.setEnabled(true);
        startButton.setEnabled(false);
        //  base.getBaseManager().startApplicationSharing();
        ss.startScraping();
        setState(JFrame.ICONIFIED);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        mPanel = new javax.swing.JPanel();
        desktopOpt = new javax.swing.JRadioButton();
        cPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setTitle("Remote Desktop Sharing");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Application Sharing");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        mPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Options")));
        mPanel.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(desktopOpt);
        desktopOpt.setSelected(true);
        desktopOpt.setText("Share Entire Desktop");
        mPanel.add(desktopOpt, new java.awt.GridBagConstraints());

        getContentPane().add(mPanel, java.awt.BorderLayout.CENTER);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        cPanel.add(startButton);

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        cPanel.add(stopButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        cPanel.add(closeButton);

        getContentPane().add(cPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
    startScraping();
}//GEN-LAST:event_startButtonActionPerformed

private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
//    base.getBaseManager().stopApplicationSharing();

    if (ss != null) {//GEN-LAST:event_stopButtonActionPerformed
            stopScraping();
        }

    }
private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
    stopScraping();
    dispose();
}//GEN-LAST:event_closeButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppShareFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JRadioButton desktopOpt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables

}
