/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginFrame.java
 *
 * Created on 2008/09/16, 02:29:34
 */
package avoir.realtime.appsharing;


import avoir.realtime.appsharing.tcp.TCPConnector;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author developer
 */
public class LoginFrame extends javax.swing.JFrame {

    JPanel logoPanel = new JPanel();

    /** Creates new form LoginFrame */
    public LoginFrame() {
        initComponents();
        logoPanel.setPreferredSize(new Dimension(100, 100));
        logoPanel.setBorder(BorderFactory.createLoweredBevelBorder());
        //  add(logoPanel,BorderLayout.WEST);
        setSize(400, 300);
        setLocationRelativeTo(null);
    }

    private void connect() {

        String username = nameField.getText();
        if (username.trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Empty names not allowed");
            return;
        }
        String host = AppProps.getProperty("SERVER_HOST");
        int port = Integer.parseInt(AppProps.getProperty("SERVER_PORT"));
        String sessionId = "standalone";

        TCPConnector tcpClient = new TCPConnector(username, sessionId);
        if (!tcpClient.connectToServer(host,port)) {
            JOptionPane.showMessageDialog(null, "Unable to connecto to the server");
            return;
        }
        new AppShareFrame(tcpClient, sessionId).setVisible(true);
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        cPanel = new javax.swing.JPanel();
        connecButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        mPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        serverOpt = new javax.swing.JButton();

        mainPanel.setLayout(new java.awt.BorderLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Realtime Virtual Classroom 1.0.1");

        connecButton.setText("Connect");
        connecButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connecButtonActionPerformed(evt);
            }
        });
        cPanel.add(connecButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        cPanel.add(closeButton);

        getContentPane().add(cPanel, java.awt.BorderLayout.PAGE_END);

        mPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Login and Connect to Virtual Classroom Server"));
        mPanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Participant's Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        mPanel.add(jLabel2, gridBagConstraints);

        nameField.setPreferredSize(new java.awt.Dimension(200, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        mPanel.add(nameField, gridBagConstraints);

        serverOpt.setText("Server Options");
        serverOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serverOptActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        mPanel.add(serverOpt, gridBagConstraints);

        getContentPane().add(mPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void serverOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serverOptActionPerformed
        ServerOptFrame fr = new ServerOptFrame();
        fr.setSize(300, 200);
        fr.setLocationRelativeTo(null);
        fr.setVisible(true);
    }//GEN-LAST:event_serverOptActionPerformed

    private void connecButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connecButtonActionPerformed
        connect();
    }//GEN-LAST:event_connecButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
 //JFrame.setDefaultLookAndFeelDecorated(true);
 //JDialog.setDefaultLookAndFeelDecorated(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
    
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton connecButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton serverOpt;
    // End of variables declaration//GEN-END:variables

}
