/*
 * RemoteDesktopViewerFrame.java
 *
 * Created on 13 September 2008, 11:17
 */
package avoir.realtime.appsharing;

import avoir.realtime.common.ImageUtil;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author  developer
 */
public class RemoteDesktopViewerFrame extends javax.swing.JFrame {

    private MButton magViewPlus,  magViewMinus;
    private Viewer viewer;
    private JScrollPane scrollPane = new JScrollPane();

    /** Creates new form RemoteDesktopViewerFrame */
    public RemoteDesktopViewerFrame() {
        initComponents();
        viewer = new Viewer(this);
        add(new JScrollPane(viewer), BorderLayout.CENTER);

        magViewPlus = new MButton(ImageUtil.createImageIcon(this, "/icons/viewmag+.png"));
        magViewMinus = new MButton(ImageUtil.createImageIcon(this, "/icons/viewmag-.png"));

        magViewPlus.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                double factor = viewer.getFactor();
                viewer.setFactor(factor += 0.1);
                viewer.setMagX(factor += 0.1);
                viewer.setMagY(factor += 0.1);

                repaint();
            }
        });

        magViewMinus.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                double factor = viewer.getFactor();
                viewer.setFactor(factor -= 0.1);
                viewer.setMagX(factor -= 0.1);
                viewer.setMagY(factor -= 0.1);
                repaint();

            }
        });

        JPanel magPanel = new JPanel();
        magPanel.add(magViewMinus);
        magPanel.add(magViewPlus);
        add(magPanel, BorderLayout.NORTH);
    }

    public Viewer getViewer() {
        return viewer;
    }

    public JScrollPane getScrollPane() {
        return scrollPane;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTitle("Remote Desktop Viewer");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
       viewer.setResized(false);
    }//GEN-LAST:event_formComponentResized

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoteDesktopViewerFrame().setVisible(true);
            }
        });
    }
/**
     * Our own button behavoir
     */
    class MButton extends JButton {

        public MButton(ImageIcon icon) {
            super(icon);
            setBorderPainted(false);
            setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            setFont(new java.awt.Font("Dialog", 0, 9));
            // setEnabled(false);
            addMouseListener(new

                  MouseAdapter( ) {

                    @Override
                public void mouseEntered(MouseEvent e) {
                    setContentAreaFilled(true);
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    setContentAreaFilled(false);
                }
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
