<?php
    // Load classes
	$this->loadClass("form","htmlelements");
	$this->loadClass("textinput","htmlelements");
	$this->loadClass("button","htmlelements");
	$form = new form("main", 
		$this->uri(array(
	    	'module'=>'personalspace',
			'action'=>'editconfirm',
		))	
	);
	$form->setDisplayType(3);
    $table =& $this->newObject('htmltable','htmlelements');
    $table->width='';
    $table->attributes=" align='center' border=0";
    $table->cellspacing='2';
    $table->cellpadding='2'; 
    //
$textinput = new textinput('title',$element['title']);
$row = array($objLanguage->languageText('mod_personalspace_title'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('firstName',$element['firstName']);
$row = array($objLanguage->languageText('mod_personalspace_firstName'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('surname',$element['surname']);
$row = array($objLanguage->languageText('mod_personalspace_surname'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('maidenSurname',$element['maidenSurname']);
$row = array($objLanguage->languageText('mod_personalspace_maidenSurname'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('idNumber',$element['idNumber']);
$row = array($objLanguage->languageText('mod_personalspace_idNumber'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('dateOfBirth',$element['dateOfBirth']);
$row = array($objLanguage->languageText('mod_personalspace_dateOfBirth'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('gender',$element['gender']);
$row = array($objLanguage->languageText('mod_personalspace_gender'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('language',$element['language']);
$row = array($objLanguage->languageText('mod_personalspace_language'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('maritalStatus',$element['maritalStatus']);
$row = array($objLanguage->languageText('mod_personalspace_maritalStatus'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('interests_1',$element['interests_1']);
$row = array($objLanguage->languageText('mod_personalspace_interests_1'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('interests_2',$element['interests_2']);
$row = array($objLanguage->languageText('mod_personalspace_interests_2'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('interests_3',$element['interests_3']);
$row = array($objLanguage->languageText('mod_personalspace_interests_3'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('interests_4',$element['interests_4']);
$row = array($objLanguage->languageText('mod_personalspace_interests_4'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('interests_5',$element['interests_5']);
$row = array($objLanguage->languageText('mod_personalspace_interests_5'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('spouseAlumnus',$element['spouseAlumnus']);
$row = array($objLanguage->languageText('mod_personalspace_spouseAlumnus'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('spouseName',$element['spouseName']);
$row = array($objLanguage->languageText('mod_personalspace_spouseName'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('spouseNumber',$element['spouseNumber']);
$row = array($objLanguage->languageText('mod_personalspace_spouseNumber'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('otherAlumni',$element['otherAlumni']);
$row = array($objLanguage->languageText('mod_personalspace_otherAlumni'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('postalAddress_1',$element['postalAddress_1']);
$row = array($objLanguage->languageText('mod_personalspace_postalAddress_1'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('postalCode',$element['postalCode']);
$row = array($objLanguage->languageText('mod_personalspace_postalCode'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('telephoneHome',$element['telephoneHome']);
$row = array($objLanguage->languageText('mod_personalspace_telephoneHome'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('telephoneMobile',$element['telephoneMobile']);
$row = array($objLanguage->languageText('mod_personalspace_telephoneMobile'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('emailAddress',$element['emailAddress']);
$row = array($objLanguage->languageText('mod_personalspace_emailAddress'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('studentNo',$element['studentNo']);
$row = array($objLanguage->languageText('mod_personalspace_studentNo'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseUWC_1',$element['courseUWC_1']);
$row = array($objLanguage->languageText('mod_personalspace_courseUWC_1'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearUWC_1',$element['yearUWC_1']);
$row = array($objLanguage->languageText('mod_personalspace_yearUWC_1'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseUWC_2',$element['courseUWC_2']);
$row = array($objLanguage->languageText('mod_personalspace_courseUWC_2'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearUWC_2',$element['yearUWC_2']);
$row = array($objLanguage->languageText('mod_personalspace_yearUWC_2'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseUWC_3',$element['courseUWC_3']);
$row = array($objLanguage->languageText('mod_personalspace_courseUWC_3'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearUWC_3',$element['yearUWC_3']);
$row = array($objLanguage->languageText('mod_personalspace_yearUWC_3'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseUWC_4',$element['courseUWC_4']);
$row = array($objLanguage->languageText('mod_personalspace_courseUWC_4'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearUWC_4',$element['yearUWC_4']);
$row = array($objLanguage->languageText('mod_personalspace_yearUWC_4'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseUWC_5',$element['courseUWC_5']);
$row = array($objLanguage->languageText('mod_personalspace_courseUWC_5'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearUWC_5',$element['yearUWC_5']);
$row = array($objLanguage->languageText('mod_personalspace_yearUWC_5'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearEnroled',$element['yearEnroled']);
$row = array($objLanguage->languageText('mod_personalspace_yearEnroled'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('residence',$element['residence']);
$row = array($objLanguage->languageText('mod_personalspace_residence'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('residenceName',$element['residenceName']);
$row = array($objLanguage->languageText('mod_personalspace_residenceName'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseOther_1',$element['courseOther_1']);
$row = array($objLanguage->languageText('mod_personalspace_courseOther_1'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearOther_1',$element['yearOther_1']);
$row = array($objLanguage->languageText('mod_personalspace_yearOther_1'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseOther_2',$element['courseOther_2']);
$row = array($objLanguage->languageText('mod_personalspace_courseOther_2'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearOther_2',$element['yearOther_2']);
$row = array($objLanguage->languageText('mod_personalspace_yearOther_2'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseOther_3',$element['courseOther_3']);
$row = array($objLanguage->languageText('mod_personalspace_courseOther_3'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearOther_3',$element['yearOther_3']);
$row = array($objLanguage->languageText('mod_personalspace_yearOther_3'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseOther_4',$element['courseOther_4']);
$row = array($objLanguage->languageText('mod_personalspace_courseOther_4'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearOther_4',$element['yearOther_4']);
$row = array($objLanguage->languageText('mod_personalspace_yearOther_4'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('courseOther_5',$element['courseOther_5']);
$row = array($objLanguage->languageText('mod_personalspace_courseOther_5'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('yearOther_5',$element['yearOther_5']);
$row = array($objLanguage->languageText('mod_personalspace_yearOther_5'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('jobTitle',$element['jobTitle']);
$row = array($objLanguage->languageText('mod_personalspace_jobTitle'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('company',$element['company']);
$row = array($objLanguage->languageText('mod_personalspace_company'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('jobFunction',$element['jobFunction']);
$row = array($objLanguage->languageText('mod_personalspace_jobFunction'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('industry',$element['industry']);
$row = array($objLanguage->languageText('mod_personalspace_industry'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('jobType',$element['jobType']);
$row = array($objLanguage->languageText('mod_personalspace_jobType'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('location',$element['location']);
$row = array($objLanguage->languageText('mod_personalspace_location'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('telephoneWork',$element['telephoneWork']);
$row = array($objLanguage->languageText('mod_personalspace_telephoneWork'),$textinput->show());
$table->addRow($row, 'even');
$textinput = new textinput('telephoneWork',$element['telephoneWork']);
$row = array($objLanguage->languageText('mod_personalspace_telephoneWork'),$textinput->show());
$table->addRow($row, 'even');
    //
    $button = new button("submit", $objLanguage->languageText("word_save")); //word_create
    $button->setToSubmit();
    $row = array($button->show());
    $table->addRow($row, 'even');
	$form->addToForm($table->show());
	echo $form->show();
?>