/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WhiteboardToolsPanel.java
 *
 * Created on 2009/07/11, 5:58:48 PM
 */
package org.avoir.realtime.skins.winxp;

import java.awt.Component;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.JButton;
import javax.swing.JToggleButton;
import org.avoir.realtime.common.util.GeneralUtil;
import org.avoir.realtime.gui.PointerListPanel;
import org.avoir.realtime.gui.main.GUIAccessManager;
import org.avoir.realtime.net.ConnectionManager;
import static org.avoir.realtime.common.Constants.Whiteboard.*;

/**
 *
 * @author david
 */
public class WhiteboardToolsPanel extends javax.swing.JPanel {

    /** Creates new form WhiteboardToolsPanel */
    public WhiteboardToolsPanel() {
        initComponents();
    }

    public void setGUIAccess() {
        Component[] cs = this.getComponents();
        for (Component c : cs) {
            c.setEnabled(ConnectionManager.isOwner);
        }
    }

    class RButton extends JToggleButton implements MouseListener, MouseMotionListener {

        public void mouseClicked(MouseEvent e) {
        }

        public void mouseEntered(MouseEvent e) {
        }

        public void mouseExited(MouseEvent e) {
        }

        public void mousePressed(MouseEvent e) {
            for (Component c : WhiteboardToolsPanel.this.getComponents()) {
                if (c instanceof JButton) {
                    JButton b = (JButton) c;
                    b.setBorderPainted(false);
                    b.setContentAreaFilled(false);
                }

            }
            setBorderPainted(true);
            setContentAreaFilled(true);
        }

        public void mouseReleased(MouseEvent e) {
        }

        public void mouseDragged(MouseEvent e) {
        }

        public void mouseMoved(MouseEvent e) {
        }

        public RButton() {
            addMouseListener(this);
            addMouseMotionListener(this);
            setBorderPainted(false);
            setContentAreaFilled(false);

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wbButtonGroup = new javax.swing.ButtonGroup();
        moveButton1 = new javax.swing.JToggleButton();
        lineButton1 = new javax.swing.JToggleButton();
        drawOvalButton1 = new javax.swing.JToggleButton();
        ovalFillButton1 = new javax.swing.JToggleButton();
        rectFillButton1 = new javax.swing.JToggleButton();
        penButton = new javax.swing.JToggleButton();
        textButton1 = new javax.swing.JToggleButton();
        undoButton = new javax.swing.JButton();
        eraseButton1 = new javax.swing.JToggleButton();
        drawRectButton1 = new javax.swing.JToggleButton();

        setName("whiteboardToolsPanel"); // NOI18N
        setLayout(new java.awt.GridLayout(2, 5));

        wbButtonGroup.add(moveButton1);
        moveButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/movearrow.gif"))); // NOI18N
        moveButton1.setToolTipText("Move");
        moveButton1.setFocusable(false);
        moveButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        moveButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        moveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveButton1ActionPerformed(evt);
            }
        });
        add(moveButton1);

        wbButtonGroup.add(lineButton1);
        lineButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/draw_Line.gif"))); // NOI18N
        lineButton1.setToolTipText("Line");
        lineButton1.setFocusable(false);
        lineButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lineButton1.setName("lineButton"); // NOI18N
        lineButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lineButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineButton1ActionPerformed(evt);
            }
        });
        add(lineButton1);

        wbButtonGroup.add(drawOvalButton1);
        drawOvalButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/stock_draw-circle-unfilled.png"))); // NOI18N
        drawOvalButton1.setToolTipText("Draw Oval");
        drawOvalButton1.setFocusable(false);
        drawOvalButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        drawOvalButton1.setName("drawOval"); // NOI18N
        drawOvalButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        drawOvalButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawOvalButton1ActionPerformed(evt);
            }
        });
        add(drawOvalButton1);

        wbButtonGroup.add(ovalFillButton1);
        ovalFillButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/draw_Oval.gif"))); // NOI18N
        ovalFillButton1.setToolTipText("Fill Oval");
        ovalFillButton1.setFocusable(false);
        ovalFillButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ovalFillButton1.setName("fillOval"); // NOI18N
        ovalFillButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ovalFillButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovalFillButton1ActionPerformed(evt);
            }
        });
        add(ovalFillButton1);

        wbButtonGroup.add(rectFillButton1);
        rectFillButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/draw_Rectangle.gif"))); // NOI18N
        rectFillButton1.setToolTipText("Fill Rectangle");
        rectFillButton1.setFocusable(false);
        rectFillButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rectFillButton1.setName("fillRect"); // NOI18N
        rectFillButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rectFillButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectFillButton1ActionPerformed(evt);
            }
        });
        add(rectFillButton1);

        wbButtonGroup.add(penButton);
        penButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/draw_Scribble.gif"))); // NOI18N
        penButton.setSelected(true);
        penButton.setToolTipText("Scribble");
        penButton.setFocusable(false);
        penButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        penButton.setName("scribble"); // NOI18N
        penButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        penButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penButtonActionPerformed(evt);
            }
        });
        add(penButton);

        wbButtonGroup.add(textButton1);
        textButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/text.png"))); // NOI18N
        textButton1.setToolTipText("Text");
        textButton1.setFocusable(false);
        textButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        textButton1.setName("addText"); // NOI18N
        textButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        textButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textButton1ActionPerformed(evt);
            }
        });
        add(textButton1);

        undoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/undo.png"))); // NOI18N
        undoButton.setToolTipText("Undo");
        undoButton.setFocusable(false);
        undoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        undoButton.setName("undo"); // NOI18N
        undoButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });
        add(undoButton);

        wbButtonGroup.add(eraseButton1);
        eraseButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/erase_all_annotations.gif"))); // NOI18N
        eraseButton1.setToolTipText("Erase selected Item");
        eraseButton1.setFocusable(false);
        eraseButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eraseButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eraseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseButton1ActionPerformed(evt);
            }
        });
        add(eraseButton1);

        wbButtonGroup.add(drawRectButton1);
        drawRectButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteboard/stock_draw-rectangle-unfilled.png"))); // NOI18N
        drawRectButton1.setToolTipText("Draw Rectangle");
        drawRectButton1.setFocusable(false);
        drawRectButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        drawRectButton1.setName("drawRect"); // NOI18N
        drawRectButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        drawRectButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawRectButton1ActionPerformed(evt);
            }
        });
        add(drawRectButton1);
    }// </editor-fold>//GEN-END:initComponents

    private void moveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveButton1ActionPerformed
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setCurrentPointer(PointerListPanel.NO_POINTER);
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setItemType(MOVE);
    }//GEN-LAST:event_moveButton1ActionPerformed

    private void lineButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineButton1ActionPerformed

        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setCurrentPointer(PointerListPanel.NO_POINTER);
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setItemType(LINE);
    }//GEN-LAST:event_lineButton1ActionPerformed

    private void drawOvalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawOvalButton1ActionPerformed
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setCurrentPointer(PointerListPanel.NO_POINTER);
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setItemType(DRAW_OVAL);
    }//GEN-LAST:event_drawOvalButton1ActionPerformed

    private void ovalFillButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovalFillButton1ActionPerformed
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setCurrentPointer(PointerListPanel.NO_POINTER);
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setItemType(FILL_OVAL);
    }//GEN-LAST:event_ovalFillButton1ActionPerformed

    private void rectFillButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectFillButton1ActionPerformed
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setCurrentPointer(PointerListPanel.NO_POINTER);
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setItemType(FILL_RECT);
    }//GEN-LAST:event_rectFillButton1ActionPerformed

    private void penButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penButtonActionPerformed
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setCurrentPointer(PointerListPanel.NO_POINTER);
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setItemType(PEN);
}//GEN-LAST:event_penButtonActionPerformed

    private void textButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textButton1ActionPerformed
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setCurrentPointer(PointerListPanel.NO_POINTER);
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setItemType(TEXT);
    }//GEN-LAST:event_textButton1ActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().undo();
}//GEN-LAST:event_undoButtonActionPerformed

    private void eraseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseButton1ActionPerformed
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setCurrentPointer(PointerListPanel.NO_POINTER);
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setItemType(ERASE);
    }//GEN-LAST:event_eraseButton1ActionPerformed

    private void drawRectButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawRectButton1ActionPerformed
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setCurrentPointer(PointerListPanel.NO_POINTER);
        GUIAccessManager.mf.getWhiteboardPanel().getWhiteboard().setItemType(DRAW_RECT);
    }//GEN-LAST:event_drawRectButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton drawOvalButton1;
    private javax.swing.JToggleButton drawRectButton1;
    private javax.swing.JToggleButton eraseButton1;
    private javax.swing.JToggleButton lineButton1;
    private javax.swing.JToggleButton moveButton1;
    private javax.swing.JToggleButton ovalFillButton1;
    private javax.swing.JToggleButton penButton;
    private javax.swing.JToggleButton rectFillButton1;
    private javax.swing.JToggleButton textButton1;
    private javax.swing.JButton undoButton;
    private javax.swing.ButtonGroup wbButtonGroup;
    // End of variables declaration//GEN-END:variables
}
