/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AudioVideoTest.java
 *
 * Created on 2009/08/23, 9:28:25 PM
 */
package org.avoir.realtime.sound;

import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.SwingUtilities;
import org.avoir.realtime.common.util.GeneralUtil;
import org.avoir.realtime.gui.main.GUIAccessManager;
import org.avoir.realtime.net.ConnectionManager;

/**
 *
 * @author kim
 */
public class AudioVideoTest extends javax.swing.JDialog {

    private JWebBrowser broadcaster = new JWebBrowser();
    private JWebBrowser receiver = new JWebBrowser();
    private Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();

    /** Creates new form AudioVideoTest */
    public AudioVideoTest() {
        super(GUIAccessManager.mf);
        setModal(true);
        broadcaster.setBarsVisible(false);
        broadcaster.setMenuBarVisible(false);
        broadcaster.setLocationBarVisible(false);
        broadcaster.setStatusBarVisible(false);

        receiver.setBarsVisible(false);
        receiver.setMenuBarVisible(false);
        receiver.setLocationBarVisible(false);
        receiver.setStatusBarVisible(false);

        initComponents();
        setSize((ss.width / 3) * 2, (ss.height / 4) * 2);
        splitPane.setDividerLocation(getWidth() / 2);
        splitPane.setLeftComponent(broadcaster);
        splitPane.setRightComponent(receiver);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cPanel = new javax.swing.JPanel();
        startTestButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        splitPane = new javax.swing.JSplitPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Audio/Video test");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        startTestButton.setText("Start Test");
        startTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTestButtonActionPerformed(evt);
            }
        });
        cPanel.add(startTestButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        cPanel.add(closeButton);

        getContentPane().add(cPanel, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTestButtonActionPerformed
        if (!ConnectionManager.AUDIO_VIDEO_URL.startsWith("http://")) {
            ConnectionManager.AUDIO_VIDEO_URL = "http://" + ConnectionManager.AUDIO_VIDEO_URL;
        }
        String test1 = "test" + GeneralUtil.generateRandomStr(4);
        String test2 = "test" + GeneralUtil.generateRandomStr(4);
        String instructorUrl = ConnectionManager.AUDIO_VIDEO_URL +
                "/video/broadcaster.html?me=" + test1 + "&you=" + test2;

        String participantUrl = ConnectionManager.AUDIO_VIDEO_URL +
                "/video/receiver.html?me=" + test2 + "&you=" + test1;

        navigateToBroadcasterURl(instructorUrl);

        navigateToReceiverURl(participantUrl);

}//GEN-LAST:event_startTestButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed
    private void navigateToBroadcasterURl(final String url) {
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                broadcaster.navigate(url);
            }
        });
    }

    private void navigateToReceiverURl(final String url) {
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                receiver.navigate(url);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AudioVideoTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton startTestButton;
    // End of variables declaration//GEN-END:variables
}
