/*
 * RemoteDesktopViewerFrame.java
 *
 * Created on 13 September 2008, 11:17
 */
package avoir.realtime.tcp.base.appsharing;

import java.awt.BorderLayout;

/**
 *
 * @author  developer
 */
public class RemoteDesktopViewerFrame extends javax.swing.JFrame {

    Viewer viewer;
    /** Creates new form RemoteDesktopViewerFrame */
    public RemoteDesktopViewerFrame() {
        initComponents();
        viewer=new Viewer(this);
        add(viewer,BorderLayout.CENTER);
    }

    public Viewer getViewer() {
        return viewer;
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remote Desktop Viewer");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoteDesktopViewerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
