/*
 * Viewer.java
 *
 * Created on 13 September 2008, 11:56
 */
package avoir.realtime.tcp.base.appsharing;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.JFrame;

/**
 *
 * @author  developer
 */
public class Viewer extends javax.swing.JPanel {

    private Image image;
    private JFrame fr; 

    /** Creates new form Viewer */
    public Viewer(JFrame fr) {
        this.fr=fr;
        initComponents();
    }

    public Image getImage() {
        return image;
    }

    public void setImage(Image image) {
        this.image = image;
    }


    @Override
    protected void paintComponent(Graphics arg0) {
        super.paintComponent(arg0);
        Graphics2D g = (Graphics2D) arg0;
        if (image != null && fr != null) {
            g.drawImage(image, 0,0,fr.getWidth(), fr.getHeight(), this);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
