<?php
    $tablename = 'tbl_apo_outcomesandassessmentthreeScience';
    $options = array('comment' => 'Table used to save data from user input in the outcomes and assessment three form for the science faculty', 'collate' => 'utf8_general_ci', 'character_set' => 'utf8');
    $fields = array('id' => array('type' => 'text','length' => 32, 'notnull'=>TRUE),
                    'a1' => array('type' => 'text', 'notnull'=>TRUE),
                    'a2' => array('type' => 'text', 'notnull'=>TRUE),
                    'a3' => array('type' => 'text', 'notnull'=>TRUE),
                    'a4' => array('type' => 'text', 'notnull'=>TRUE),
                    'a5' => array('type' => 'text', 'notnull'=>TRUE),
                    'a6' => array('type' => 'text', 'notnull'=>TRUE),
                    'a7' => array('type' => 'text', 'notnull'=>TRUE),
                    'a8' => array('type' => 'text', 'notnull'=>TRUE),
                    'b1' => array('type' => 'text', 'notnull'=>TRUE),
                    'b2' => array('type' => 'text', 'notnull'=>TRUE),
                    'b3' => array('type' => 'text', 'notnull'=>TRUE),
                    'b4' => array('type' => 'text', 'notnull'=>TRUE),
                    'b5' => array('type' => 'text', 'notnull'=>TRUE),
                    'b6' => array('type' => 'text', 'notnull'=>TRUE),
                    'b7' => array('type' => 'text', 'notnull'=>TRUE),
                    'b8' => array('type' => 'text', 'notnull'=>TRUE),
                    'c1' => array('type' => 'text', 'notnull'=>TRUE),
                    'c2' => array('type' => 'text', 'notnull'=>TRUE),
                    'c3' => array('type' => 'text', 'notnull'=>TRUE),
                    'c4' => array('type' => 'text', 'notnull'=>TRUE),
                    'c5' => array('type' => 'text', 'notnull'=>TRUE),
                    'c6' => array('type' => 'text', 'notnull'=>TRUE),
                    'c7' => array('type' => 'text', 'notnull'=>TRUE),
                    'c8' => array('type' => 'text', 'notnull'=>TRUE),
                    'd1' => array('type' => 'text', 'notnull'=>TRUE),
                    'd3' => array('type' => 'text', 'notnull'=>TRUE),
                    'd4' => array('type' => 'text', 'notnull'=>TRUE),
                    'd8' => array('type' => 'text', 'notnull'=>TRUE),
                    'e1' => array('type' => 'text', 'notnull'=>TRUE),
                    'e8' => array('type' => 'text', 'notnull'=>TRUE),
                    'f1' => array('type' => 'text', 'notnull'=>TRUE),
                    'f2' => array('type' => 'text', 'notnull'=>TRUE),
                    'f3' => array('type' => 'text', 'notnull'=>TRUE),
                    'f4' => array('type' => 'text', 'notnull'=>TRUE),
                    'f5' => array('type' => 'text', 'notnull'=>TRUE),
                    'f6' => array('type' => 'text', 'notnull'=>TRUE),
                    'f7' => array('type' => 'text', 'notnull'=>TRUE),
                    'f8' => array('type' => 'text', 'notnull'=>TRUE),
                    'g9' => array('type' => 'text', 'notnull'=>TRUE),
                    'g10' => array('type' => 'text', 'notnull'=>TRUE),
                    'h11' => array('type' => 'text', 'notnull'=>TRUE),
                    'h12' => array('type' => 'text', 'notnull'=>TRUE)
                    );
?>