/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SlideBuilderTextFormatPanel.java
 *
 * Created on 2009/03/04, 11:07:58
 */
package avoir.realtime.instructor;

import java.awt.Color;
import java.awt.Font;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JColorChooser;
import sun.java2d.SurfaceData;

/**
 *
 * @author developer
 */
public class SlideBuilderTextFormatPanel extends javax.swing.JPanel {

    protected JColorChooser tcc;
    private Color color = Color.BLACK;
    private int textSize = 18;

    /** Creates new form SlideBuilderTextFormatPanel */
    public SlideBuilderTextFormatPanel() {
        initComponents();
        textSizeField.removeAllItems();
        textSizeField.setEditable(true);

        for (int i = 8; i < 60; i += 2) {
            textSizeField.addItem(i + "");
        }
        textSizeField.setSelectedItem("18");
    }

    public Map<String, Object> getTextFormat() {
        Map<String, Object> map = new HashMap<String, Object>();
        map.put("color", color);
        map.put("size", new Integer(textSize));
        return map;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        textColorButton = new javax.swing.JButton();
        textSizeField = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        textColorButton.setText("Text Color");
        textColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textColorButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        add(textColorButton, gridBagConstraints);

        textSizeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSizeFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(textSizeField, gridBagConstraints);

        jLabel1.setText("Text Size");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Text Color");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        add(jLabel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void textColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textColorButtonActionPerformed
        color = JColorChooser.showDialog(this, "Choose Color", color);
        textColorButton.setForeground(color);
        
    }//GEN-LAST:event_textColorButtonActionPerformed

    private void textSizeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSizeFieldActionPerformed
        textSize = Integer.parseInt((String) textSizeField.getSelectedItem());
       // textColorButton.setFont(new Font("Dialog",0,textSize));
    }//GEN-LAST:event_textSizeFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton textColorButton;
    private javax.swing.JComboBox textSizeField;
    // End of variables declaration//GEN-END:variables
}
