/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SlideShowViewerFrame.java
 *
 * Created on 2009/03/03, 05:26:31
 */
package avoir.realtime.classroom;

import avoir.realtime.common.packet.XmlQuestionPacket;
import avoir.realtime.common.BuilderSlide;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author developer
 */
public class SlideShowViewerFrame extends javax.swing.JFrame {

    private ArrayList<BuilderSlide> slides;
    private ImageIcon slideImage;
    private Surface surface = new Surface();
    private int slideIndex = 0;

    /** Creates new form SlideShowViewerFrame */
    public SlideShowViewerFrame() {
        initComponents();
        imagePanel.add(new JScrollPane(surface), BorderLayout.CENTER);
    }

    public void setSlides(ArrayList<BuilderSlide> slides) {
        this.slides = slides;
        if (slides.size() > 0) {
            setContent(0);
        }
    }

    public void setSlideImage(ImageIcon slideImage) {
        this.slideImage = slideImage;
        surface.repaint();
        splitPane2.setDividerLocation(splitPane2.getDividerLocation() + 5);
        splitPane2.setDividerLocation(splitPane2.getDividerLocation() - 5);
    }

    public void setContent(int index) {
        BuilderSlide slide = slides.get(index);
        XmlQuestionPacket question = slide.getQuestion();
        titleField.setText(slide.getTitle());
        textField.setText(slide.getText());
        if (question != null) {
            questionField.setText(question.getQuestionPath());
        }
        setSlideImage(slide.getImage());
    }

    public void setSlideIndex(int slideIndex) {
        this.slideIndex = slideIndex;
    }

    class Surface extends JPanel {

        @Override
        public void paintComponent(Graphics g) {
            Graphics2D g2 = (Graphics2D) g;
            if (slideImage != null) {
                g2.drawImage(slideImage.getImage(), 0, 0, this);
                setPreferredSize(new Dimension(slideImage.getIconWidth(), slideImage.getIconHeight()));
                revalidate();
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        splitPane2 = new javax.swing.JSplitPane();
        toprightPanel = new javax.swing.JPanel();
        slideDetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldSP = new javax.swing.JScrollPane();
        textField = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        questionField = new javax.swing.JTextField();
        qcPanel = new javax.swing.JPanel();
        prevQnButton = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();

        setTitle("Slidee Viewer");

        splitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        splitPane2.setPreferredSize(new java.awt.Dimension(300, 150));

        toprightPanel.setLayout(new java.awt.BorderLayout());

        slideDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Slide Details"));
        slideDetailsPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Title");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        slideDetailsPanel.add(jLabel1, gridBagConstraints);

        titleField.setEditable(false);
        titleField.setPreferredSize(new java.awt.Dimension(404, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        slideDetailsPanel.add(titleField, gridBagConstraints);

        jLabel2.setText("Text");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        slideDetailsPanel.add(jLabel2, gridBagConstraints);

        textField.setColumns(20);
        textField.setEditable(false);
        textField.setRows(5);
        textFieldSP.setViewportView(textField);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        slideDetailsPanel.add(textFieldSP, gridBagConstraints);

        jLabel3.setText("Question");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        slideDetailsPanel.add(jLabel3, gridBagConstraints);

        questionField.setEditable(false);
        questionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        slideDetailsPanel.add(questionField, gridBagConstraints);

        prevQnButton.setText("View Question");
        prevQnButton.setEnabled(false);
        prevQnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevQnButtonActionPerformed(evt);
            }
        });
        qcPanel.add(prevQnButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        slideDetailsPanel.add(qcPanel, gridBagConstraints);

        toprightPanel.add(slideDetailsPanel, java.awt.BorderLayout.CENTER);

        splitPane2.setLeftComponent(toprightPanel);

        imagePanel.setLayout(new java.awt.BorderLayout());
        splitPane2.setRightComponent(imagePanel);

        getContentPane().add(splitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void questionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_questionFieldActionPerformed

    private void prevQnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevQnButtonActionPerformed
}//GEN-LAST:event_prevQnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SlideShowViewerFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton prevQnButton;
    private javax.swing.JPanel qcPanel;
    private javax.swing.JTextField questionField;
    private javax.swing.JPanel slideDetailsPanel;
    private javax.swing.JSplitPane splitPane2;
    private javax.swing.JTextArea textField;
    private javax.swing.JScrollPane textFieldSP;
    private javax.swing.JTextField titleField;
    private javax.swing.JPanel toprightPanel;
    // End of variables declaration//GEN-END:variables
}
